INSERT INTO ETUDIANT VALUES
  ('001','LEBEUF-Martin');
INSERT INTO ETUDIANT VALUES
  ('002','MARTINEZ-Dupont');
INSERT INTO ETUDIANT VALUES
  ('003','CARLIN-Dubois');
INSERT INTO ETUDIANT VALUES
  ('004','RIDLEY-Durant');
INSERT INTO ETUDIANT VALUES
  ('005','CONEN-Dupont');
INSERT INTO ETUDIANT VALUES
  ('006','INDESIT-Jean');
INSERT INTO ETUDIANT VALUES
  ('007','LEE-Didier');
INSERT INTO ETUDIANT VALUES
  ('008','MALONGA-Pierre');
INSERT INTO ETUDIANT VALUES
  ('009','LEDIS-Alex');
INSERT INTO ETUDIANT VALUES
  ('010','MARC-Olivier');

INSERT INTO resultat VALUES
  ('001','1',14.5);
INSERT INTO resultat VALUES
  ('001','2',12.75);

INSERT INTO resultat VALUES
  ('002','1',9.25);

INSERT INTO resultat VALUES
  ('003','1',10);
INSERT INTO resultat VALUES
  ('003','2',10);
INSERT INTO resultat VALUES
  ('003','3',6.5);
  
 INSERT INTO resultat VALUES
  ('004','1',12);
  INSERT INTO resultat VALUES
  ('005','1',4.5);
  INSERT INTO resultat VALUES
  ('006','1',7.5);
  INSERT INTO resultat VALUES
  ('007','1',13.5);
   INSERT INTO resultat VALUES
  ('008','1',16.5);
   INSERT INTO resultat VALUES
  ('009','1',11.5);
   INSERT INTO resultat VALUES
  ('010','1',8);
