INSERT INTO FOURNISSEUR VALUES
  ('F1','Martin',10,'Londres');
INSERT INTO FOURNISSEUR VALUES
  ('F2','Dupont',20,'Paris');
INSERT INTO FOURNISSEUR VALUES
  ('F3','Dubois',20,'Paris');
INSERT INTO FOURNISSEUR VALUES
  ('F4','Durant',10,'Londres');
INSERT INTO FOURNISSEUR VALUES
  ('F5','Dupont',20,'Athenes');

INSERT INTO PIECE VALUES
  ('P1','Vis6',12.6,'rouge');
INSERT INTO PIECE VALUES
  ('P2','Vis8',17,'vert');
INSERT INTO PIECE VALUES
  ('P3','Boulon7',17.2,'bleu');
INSERT INTO PIECE VALUES
  ('P4','Came',14,'rouge');
INSERT INTO PIECE VALUES
  ('P5','Came',12.1,'bleu');
INSERT INTO PIECE VALUES
  ('P6','Ressort',18.3,'rouge');

INSERT INTO COMMANDE VALUES
  ('F1','P3',50);
INSERT INTO COMMANDE VALUES
  ('F2','P3',10);
INSERT INTO COMMANDE VALUES
  ('F3','P3',50);
INSERT INTO COMMANDE VALUES
  ('F1','P2',12);
INSERT INTO COMMANDE VALUES
  ('F3','P2',10);
